<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ayurveda_AI_Backend.WebAPI</RootNamespace>
    <UserSecretsId>6cd85d3a-66b3-44f4-9402-4e6f6f5052b2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ayurveda-AI-Backend.Service\Ayurveda-AI-Backend.Service.csproj" />
    <ProjectReference Include="..\Ayurveda-AI-Backend.Repository\Ayurveda-AI-Backend.Repository.csproj" />
    <ProjectReference Include="..\Ayurveda-AI-Backend.Infrastructure\Ayurveda-AI-Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\Ayurveda-AI-Backend.Domain\Ayurveda-AI-Backend.Domain.csproj" />
  </ItemGroup>

</Project>
