// <auto-generated />
using System;
using Ayurveda_AI_Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ayurveda_AI_Backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206072825_RemovePoopTypeAndEnergyLevel")]
    partial class RemovePoopTypeAndEnergyLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxArticlesPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaxChatsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AccessPolicies");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.ChronicCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiagnosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChronicConditions");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRedemptions")
                        .HasColumnType("integer");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<int>("RedeemedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("CouponRedemptions");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.GeminiQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeminiQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f9c2a1-6b7a-4a2f-9c44-5a2f7f000001"),
                            Category = "Digestive",
                            IsActive = true,
                            QuestionText = "How is your digestion today?"
                        },
                        new
                        {
                            Id = new Guid("d7f9c2a1-6b7a-4a2f-9c44-5a2f7f000002"),
                            Category = "Sleep",
                            IsActive = true,
                            QuestionText = "How restful was your sleep last night?"
                        },
                        new
                        {
                            Id = new Guid("d7f9c2a1-6b7a-4a2f-9c44-5a2f7f000003"),
                            Category = "Energy",
                            IsActive = true,
                            QuestionText = "What is your current energy level?"
                        });
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.HealthIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Indication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthIndicators");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.HealthSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<string>("SignalValue")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthSignals");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.McqResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("McqResponses");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.PrakritiQuizResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("PrakritiQuizResponses");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.PrakritiResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KaphaPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PittaPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("PrakritiLabel")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VataPercent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PrakritiResults");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<string>("AuthProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserLifestyleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NatureOfJob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalIntensity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypicalWorkHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLifestyleProfiles");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightInches")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<decimal?>("WeightLbs")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArticlesUsed")
                        .HasColumnType("integer");

                    b.Property<int>("ChatsUsed")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("UserUsages");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.VikritiSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DominantDosha")
                        .HasColumnType("integer");

                    b.Property<decimal>("KaphaScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PittaScore")
                        .HasColumnType("numeric");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VataScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VikritiSnapshots");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.ChronicCondition", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("ChronicConditions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.CouponRedemption", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("CouponRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.HealthIndicator", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.HealthSignal", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("HealthSignals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.McqResponse", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.QuizQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("McqResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.PrakritiQuizResponse", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.QuizQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("PrakritiQuizResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.PrakritiResult", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("PrakritiResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.QuizOption", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserLifestyleProfile", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("LifestyleProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Ayurveda_AI_Backend.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.UserUsage", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("UserUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.VikritiSnapshot", b =>
                {
                    b.HasOne("Ayurveda_AI_Backend.Domain.Entities.User", "User")
                        .WithMany("VikritiSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Ayurveda_AI_Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("ChronicConditions");

                    b.Navigation("CouponRedemptions");

                    b.Navigation("HealthSignals");

                    b.Navigation("LifestyleProfiles");

                    b.Navigation("McqResponses");

                    b.Navigation("PrakritiQuizResponses");

                    b.Navigation("PrakritiResults");

                    b.Navigation("Profile");

                    b.Navigation("UserUsages");

                    b.Navigation("VikritiSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
